### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by MyUserNameIsVeryBad** [lostmyself8/Mekanism-Extras#11]
The logs Are Getting Spamed With an Error of Mekanism-Extras, However i cannot Upload The log Due to it having 149742 Lines but here is the Problematic part

java.lang.Exception: null
	at mekanism.common.capabilities.CapabilityCache.addCapabilityResolver(CapabilityCache.java:45) ~[Mekanism-1.20.1-10.4.8.43.jar%23593!/:10.4.8] {re:classloading}
	at mekanism.common.tile.base.CapabilityTileEntity.addCapabilityResolver(CapabilityTileEntity.java:37) ~[Mekanism-1.20.1-10.4.8.43.jar%23593!/:10.4.8] {re:classloading}
	at com.jerry.mekanism_extras.common.block.transmitter.ExtraTileEntityTransmitter.<init>(ExtraTileEntityTransmitter.java:39) ~[mekanism_extras-1.2.1.jar%23594!/:1.2.1] {re:classloading}
	at com.jerry.mekanism_extras.common.block.transmitter.cable.ExtraTileEntityUniversalCable.<init>(ExtraTileEntityUniversalCable.java:36) ~[mekanism_extras-1.2.1.jar%23594!/:1.2.1] {re:classloading}
	at com.jerry.mekanism_extras.registry.ExtraTileEntityTypes.lambda$static$22(ExtraTileEntityTypes.java:66) ~[mekanism_extras-1.2.1.jar%23594!/:1.2.1] {re:classloading}
	at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.BlockEntityTypeAccess from mod pneumaticcraft,pl:mixin:APP:flywheel.mixins.json:BlockEntityTypeMixin from mod flywheel,pl:mixin:APP:embeddiumplus.mixin.json:entitydistance.TileEntityTypeMixin from mod embeddiumplus,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:BlockEntityTypeAccessor from mod fabric_api_lookup_api_v1,pl:mixin:APP:doapi.mixins.json:sign.MixinBlockEntityType from mod doapi,pl:mixin:APP:dimdoors-common.mixins.json:accessor.BlockEntityTypeAccessor from mod dimdoors,pl:mixin:APP:crackerslib.mixins.json:MixinBlockEntityType from mod crackerslib,pl:mixin:A,pl:connector_pre_launch:A}
	at mekanism.common.block.interfaces.IHasTileEntity.m_142194_(IHasTileEntity.java:30) ~[Mekanism-1.20.1-10.4.8.43.jar%23593!/:10.4.8] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_62934_(LevelChunk.java:288) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldChunkMixin from mod radium,pl:mixin:APP:mixins.litematica.json:MixinWorldChunk from mod litematica,pl:mixin:APP:snowrealmagic.mixins.json:LevelChunkMixin from mod snowrealmagic,pl:mixin:APP:lithium.mixins.json:collections.block_entity_tickers.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.combined_heightmap_update.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldChunkMixin from mod radium,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:chunk.MixinLevelChunk from mod ohthetreesyoullgrow,pl:mixin:APP:corgilib-common.mixins.json:chunk.MixinLevelChunk from mod corgilib,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin from mod flywheel,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:WorldChunkMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:mixins.cardinal_components_block.json:common.MixinWorldChunk from mod cardinal_components_block,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelChunkMixin from mod refurbished_furniture,pl:mixin:APP:mixins.cardinal_components_chunk.json:common.MixinWorldChunk from mod cardinal_components_chunk,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:WorldChunkMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:copycats-common.mixins.json:foundation.copycat.migration.LevelChunkMixin from mod copycats,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin from mod moonlight,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_5685_(LevelChunk.java:315) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldChunkMixin from mod radium,pl:mixin:APP:mixins.litematica.json:MixinWorldChunk from mod litematica,pl:mixin:APP:snowrealmagic.mixins.json:LevelChunkMixin from mod snowrealmagic,pl:mixin:APP:lithium.mixins.json:collections.block_entity_tickers.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.combined_heightmap_update.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldChunkMixin from mod radium,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:chunk.MixinLevelChunk from mod ohthetreesyoullgrow,pl:mixin:APP:corgilib-common.mixins.json:chunk.MixinLevelChunk from mod corgilib,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin from mod flywheel,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:WorldChunkMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:mixins.cardinal_components_block.json:common.MixinWorldChunk from mod cardinal_components_block,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelChunkMixin from mod refurbished_furniture,pl:mixin:APP:mixins.cardinal_components_chunk.json:common.MixinWorldChunk from mod cardinal_components_chunk,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:WorldChunkMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:copycats-common.mixins.json:foundation.copycat.migration.LevelChunkMixin from mod copycats,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin from mod moonlight,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_187967_(LevelChunk.java:464) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldChunkMixin from mod radium,pl:mixin:APP:mixins.litematica.json:MixinWorldChunk from mod litematica,pl:mixin:APP:snowrealmagic.mixins.json:LevelChunkMixin from mod snowrealmagic,pl:mixin:APP:lithium.mixins.json:collections.block_entity_tickers.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.combined_heightmap_update.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldChunkMixin from mod radium,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:chunk.MixinLevelChunk from mod ohthetreesyoullgrow,pl:mixin:APP:corgilib-common.mixins.json:chunk.MixinLevelChunk from mod corgilib,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin from mod flywheel,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:WorldChunkMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:mixins.cardinal_components_block.json:common.MixinWorldChunk from mod cardinal_components_block,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelChunkMixin from mod refurbished_furniture,pl:mixin:APP:mixins.cardinal_components_chunk.json:common.MixinWorldChunk from mod cardinal_components_chunk,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:WorldChunkMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:copycats-common.mixins.json:foundation.copycat.migration.LevelChunkMixin from mod copycats,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin from mod moonlight,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195674_(ClientboundLevelChunkPacketData.java:107) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195660_(ClientboundLevelChunkPacketData.java:96) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_187971_(LevelChunk.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldChunkMixin from mod radium,pl:mixin:APP:mixins.litematica.json:MixinWorldChunk from mod litematica,pl:mixin:APP:snowrealmagic.mixins.json:LevelChunkMixin from mod snowrealmagic,pl:mixin:APP:lithium.mixins.json:collections.block_entity_tickers.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.combined_heightmap_update.WorldChunkMixin from mod radium,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldChunkMixin from mod radium,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:chunk.MixinLevelChunk from mod ohthetreesyoullgrow,pl:mixin:APP:corgilib-common.mixins.json:chunk.MixinLevelChunk from mod corgilib,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin from mod flywheel,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:WorldChunkMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:mixins.cardinal_components_block.json:common.MixinWorldChunk from mod cardinal_components_block,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelChunkMixin from mod refurbished_furniture,pl:mixin:APP:mixins.cardinal_components_chunk.json:common.MixinWorldChunk from mod cardinal_components_chunk,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:WorldChunkMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:copycats-common.mixins.json:foundation.copycat.migration.LevelChunkMixin from mod copycats,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin from mod moonlight,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.multiplayer.ClientChunkCache.m_194116_(ClientChunkCache.java:112) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:light.LightUpdateMixin from mod flywheel,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:ClientChunkManagerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:securitycraft.mixins.json:camera.ClientChunkCacheMixin from mod securitycraft,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_194198_(ClientPacketListener.java:714) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-message-api-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_networking_api_v1,pl:mixin:APP:mixins.litematica.json:MixinClientPlayNetworkHandler from mod litematica,pl:mixin:APP:mixins.essential.json:client.commands.ClientPlayNetHandlerMixin_CommandRegistration from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_JoinEvent from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_RegisterEssentialChannel from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_SendChatEvents from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_TabListNameIdCache from mod (unknown),pl:mixin:APP:pehkui.mixins.json:client.compat117plus.ClientPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:mixins.cofhcore.json:ClientPacketListenerMixin from mod cofh_core,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinClientPacketListener from mod nochatreports,pl:mixin:APP:mixins/forge/nochatreports-forge.mixins.json:client.MixinClientPacketListener from mod (unknown),pl:mixin:APP:flywheel.mixins.json:light.NetworkLightUpdateMixin from mod flywheel,pl:mixin:APP:almostunified-common.mixins.json:runtime.ClientPacketListenerMixin from mod almostunified,pl:mixin:APP:crittersandcompanions.mixins.json:ClientPacketListenerMixin from mod crittersandcompanions,pl:mixin:APP:immersive_aircraft.mixins.json:client.ClientPlayNetworkHandlerMixin from mod immersive_aircraft,pl:mixin:APP:fabric-data-attachment-api-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:mixins.malilib.json:MixinClientPlayNetworkHandler from mod malilib,pl:mixin:APP:dimdoors-common.mixins.json:client.ExtendedClientPlayNetworkHandlerMixin from mod dimdoors,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:copycats-forge.mixins.json:network.ClientPacketListenerMixin from mod copycats,pl:mixin:APP:journeymap.mixins.json:client.ClientPacketListenerMixin from mod journeymap,pl:mixin:APP:moderntrainparts.mixins.json:ClientPacketListenerMixin from mod moderntrainparts,pl:mixin:APP:friendsandfoes-common.mixins.json:ClientPlayNetworkHandlerMixin from mod friendsandfoes,pl:mixin:APP:alexscaves.mixins.json:client.ClientPacketListenerMixin from mod alexscaves,pl:mixin:APP:moonlight-common.mixins.json:ClientPacketListenerMixin from mod moonlight,pl:mixin:APP:sound_physics_remastered.mixins.json:ClientPacketListenerMixin from mod (unknown),pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientPlayNetworkHandlerMixin from mod embeddium,pl:mixin:APP:mixins.recording.replaymod.json:MixinNetHandlerPlayClient from mod (unknown),pl:mixin:APP:mixins.replay.replaymod.json:entity_tracking.Mixin_FixPartialUpdates from mod (unknown),pl:mixin:APP:mixins.replay.replaymod.json:Mixin_FixEntityNotTracking from mod (unknown),pl:mixin:APP:the_bumblezone-common.mixins.json:client.ClientPacketListenerMixin from mod the_bumblezone,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_183388_(ClientPacketListener.java:678) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-message-api-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_message_api_v1,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_networking_api_v1,pl:mixin:APP:mixins.litematica.json:MixinClientPlayNetworkHandler from mod litematica,pl:mixin:APP:mixins.essential.json:client.commands.ClientPlayNetHandlerMixin_CommandRegistration from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_JoinEvent from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_RegisterEssentialChannel from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_SendChatEvents from mod (unknown),pl:mixin:APP:mixins.essential.json:client.network.Mixin_TabListNameIdCache from mod (unknown),pl:mixin:APP:pehkui.mixins.json:client.compat117plus.ClientPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:mixins.cofhcore.json:ClientPacketListenerMixin from mod cofh_core,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinClientPacketListener from mod nochatreports,pl:mixin:APP:mixins/forge/nochatreports-forge.mixins.json:client.MixinClientPacketListener from mod (unknown),pl:mixin:APP:flywheel.mixins.json:light.NetworkLightUpdateMixin from mod flywheel,pl:mixin:APP:almostunified-common.mixins.json:runtime.ClientPacketListenerMixin from mod almostunified,pl:mixin:APP:crittersandcompanions.mixins.json:ClientPacketListenerMixin from mod crittersandcompanions,pl:mixin:APP:immersive_aircraft.mixins.json:client.ClientPlayNetworkHandlerMixin from mod immersive_aircraft,pl:mixin:APP:fabric-data-attachment-api-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:mixins.malilib.json:MixinClientPlayNetworkHandler from mod malilib,pl:mixin:APP:dimdoors-common.mixins.json:client.ExtendedClientPlayNetworkHandlerMixin from mod dimdoors,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:ClientPlayNetworkHandlerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:copycats-forge.mixins.json:network.ClientPacketListenerMixin from mod copycats,pl:mixin:APP:journeymap.mixins.json:client.ClientPacketListenerMixin from mod journeymap,pl:mixin:APP:moderntrainparts.mixins.json:ClientPacketListenerMixin from mod moderntrainparts,pl:mixin:APP:friendsandfoes-common.mixins.json:ClientPlayNetworkHandlerMixin from mod friendsandfoes,pl:mixin:APP:alexscaves.mixins.json:client.ClientPacketListenerMixin from mod alexscaves,pl:mixin:APP:moonlight-common.mixins.json:ClientPacketListenerMixin from mod moonlight,pl:mixin:APP:sound_physics_remastered.mixins.json:ClientPacketListenerMixin from mod (unknown),pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientPlayNetworkHandlerMixin from mod embeddium,pl:mixin:APP:mixins.recording.replaymod.json:MixinNetHandlerPlayClient from mod (unknown),pl:mixin:APP:mixins.replay.replaymod.json:entity_tracking.Mixin_FixPartialUpdates from mod (unknown),pl:mixin:APP:mixins.replay.replaymod.json:Mixin_FixEntityNotTracking from mod (unknown),pl:mixin:APP:the_bumblezone-common.mixins.json:client.ClientPacketListenerMixin from mod the_bumblezone,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5797_(ClientboundLevelChunkWithLightPacket.java:12) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_FixPacketHandlingPastServerShutdown from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:client.Mixin_ThreadTaskExecutor from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:computing_frames,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:client.Mixin_ThreadTaskExecutor from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:client.Mixin_ThreadTaskExecutor from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:mffs:resizeDisplayHook,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.6.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.6.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}

**Comment by lostmyself8** [comment]
知道了我已经搞掉了，如果不严重我想等搞完反应堆发。（）
